title: Seonghyun Park
logo: /assets/img/identicon.png
description: >-
bio: >-
  <p><a href="http://en.snu.ac.kr">@SNU<a></p>
google_analytics:
theme: jekyll-theme-minimal

email: seonghnpark.at.gmail.com
github_username: seonghpark
