title: Seonghyun Park
logo: /assets/img/identicon.png
description: >-
  <p>Hi, there! I am an undergraduate student <a href="https://snu.ac.kr">@SNU</a>.
  I am interested in computer systems.</p>

google_analytics:
theme: jekyll-theme-minimal

email: seonghnpark.at.gmail.com
github_username: seonghpark
twitter_username: seonghnpark
